# Different types of multivariate relationship

We have already discussed the spurious relationship, and how we might show that graphically with boxes and arrows.
For example, 

```{image} images/regression2_commonCause.png
:width: 50%
:align: center
```
Multivariate relationships may also take the form of a chain
relationship, where x_1 causes x_2 which causes y.

For example: 

```{image} images/regression2_chainBlock.png
:width: 50%
:align: center
```

An interaction term is where the effect $x_1$ on $y$ is dependent on $x_2$. In this example, the size of the effect of socioeconomic status on health depends on age. 

```{image} images/regression2_interactionBlock.png
:width: 50%
:align: center
```

It is also helpful to graph interaction terms, for example:

```{image} images/regression2_interactionPlot.png
:width: 50%
:align: center
```

Here we can see that the slope for socioeconomic status is steeper for
older people than for younger people. There is an *interaction*
between socioeconomic status and age.

For other types of multivariate analysis, check back to the lecture slides on Canvas. (They include direct and indirect effects and multiple causes).
